// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// h3rcppLatLngToCell
SEXP h3rcppLatLngToCell(SEXP lat, SEXP lon, SEXP res);
RcppExport SEXP _h3rcpp_h3rcppLatLngToCell(SEXP latSEXP, SEXP lonSEXP, SEXP resSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type lat(latSEXP);
    Rcpp::traits::input_parameter< SEXP >::type lon(lonSEXP);
    Rcpp::traits::input_parameter< SEXP >::type res(resSEXP);
    rcpp_result_gen = Rcpp::wrap(h3rcppLatLngToCell(lat, lon, res));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_h3rcpp_h3rcppLatLngToCell", (DL_FUNC) &_h3rcpp_h3rcppLatLngToCell, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_h3rcpp(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
