# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

h3rcppLatLngToCell <- function(lat, lon, res) {
    .Call(`_h3rcpp_h3rcppLatLngToCell`, lat, lon, res)
}

